




<%@ Page Title="Administratori" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Administratori.aspx.cs" Inherits="Proiect_BD.Administratori" %>


<asp:Content ID="Content1" ContentPlaceHolderID="MainContent" runat="server">







    <p>
        <br />
    </p>
    <p>

    </p>
    <p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateColumns="False" DataSourceID="LinqDataSource1">
    


        </asp:GridView>
        <asp:LinqDataSource ID="LinqDataSource1" runat="server" EntityTypeName="">
        </asp:LinqDataSource>
        <asp:EntityDataSource ID="EntityDataSource1" runat="server">
        </asp:EntityDataSource>
    </p>







</asp:Content>
